apiVersion: v1
kind: Service
metadata:
  name: react-game-service
  namespace: react-game-cd # Add this line
spec:
  selector:
    app: react-game
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80