apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-game-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaycloud336/Game-cd
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: react-game-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
